#!/bin/bash
ORIG_DIR=$(pwd)
CHAPTER=${1?"missing: the three digit 001-120"}
TITLE=$(grep $CHAPTER ../titles.txt | tr -d [:digit:])
DATE=$(date +%F)
rm *wav
rm *log
for SSML in $(ls ../spx/$1_?.ssml)
  do
    PART=$(echo $SSML | tr -d spx/.ssml)
    spx synthesize --file $SSML --audio output $PART.wav  &
    wait
  done
sox $1_?.wav $1.wav
ffmpeg -i $1.wav -codec:a libmp3lame -qscale:a 9 $1.mp3    
mid3v2 -a "曹雪芹" -t "$TITLE" -A "【紅樓夢】全本廣東話原文照讀" -c "版本：清乾隆五十七（１７９２）年萃文書屋活字本（通稱 程乙本)" -g "101" -y $DATE -T "$1/120" $1.mp3
ls -l
mid3v2 $1.mp3
mv $1.mp3 $HOME/raylexlee.github.io/stone/
cd $HOME/raylexlee.github.io
git add -A
git commit -m "Add entries."
git push origin master
cd $ORIG_DIR